name: bc_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.1.5

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  devicelocale: ^0.7.1
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_cached_pdfview: ^0.4.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  qr_code_scanner: ^1.0.1
  flutter_downloader: ^1.8.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  path_provider: ^2.1.3
  open_file: ^3.3.2
  image_picker: ^1.1.1
  intl: ^0.18.1
  mime: ^1.0.5
  month_picker_dialog: ^2.11.2
  nylo_framework: ^5.27.3
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.3
  textfield_datepicker: ^0.2.0
  url_launcher: ^6.3.0
  webview_flutter: ^4.7.0     
  dotted_border: ^2.1.0
  file_picker: ^8.0.3
  http_parser: ^4.0.2
  image: ^3.0.1
  exif: ^3.3.0
  webview_flutter_wkwebview: ^3.14.0
  mobile_scanner: ^5.1.1
  cron: ^0.6.1
  syncfusion_flutter_pdfviewer: ^26.2.4
  root_jailbreak_sniffer: ^1.0.6
  package_info_plus: ^8.0.1
  flutter_widget_from_html_core: ^0.15.1
  upgrader: ^10.3.0
dependency_overrides:
  intl: ^0.18.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  fonts:
    - family: Inter-Bold
      fonts:
        - asset: public/assets/fonts/Inter-Bold.ttf
    - family: Inter-Light
      fonts:
        - asset: public/assets/fonts/Inter-Light.ttf
    - family: Inter-Regular
      fonts:
        - asset: public/assets/fonts/Inter-Regular.ttf
    - family: Inter-SemiBold
      fonts:
        - asset: public/assets/fonts/Inter-SemiBold.ttf
    - family: Poppins-Bold
      fonts:
        - asset: public/assets/fonts/Poppins-Bold.ttf
    - family: Poppins-Light
      fonts:
        - asset: public/assets/fonts/Poppins-Light.ttf
    - family: Poppins-Regular
      fonts:
        - asset: public/assets/fonts/Poppins-Regular.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: public/assets/fonts/Poppins-SemiBold.ttf

  assets:
    # Add assets from the images directory to the application.
    - public/assets/fonts/
    - public/assets/images/
    - public/assets/images/icons/
    - public/assets/app_icon/
    - lang/
    - .env
    - .env_prod